# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Java to Tomcat CICD

on:
  push:
    branches: [ "olakunle" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean install -DskipTests --file pom.xml
        #run: mvn -B clean install -Dmaven.test.skip=true  --file pom.xml
        #run: mvn -B clean install -Dmaven.test.skip  --file pom.xml

      - name: Undeploy Previous App from Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USERNAME }}
          password: ${{ secrets.TEST_PW }}
          port: ${{ secrets.TEST_PORT }}
          script: |
            curl -v -u ${{ secrets.CAT_USER }}:${{ secrets.CAT_PW }} '${{ secrets.CAT_HOST }}:${{ secrets.CAT_PORT }}/manager/text/undeploy?path=/staging-admin-service'
      - name: Copy WAR file to Tomcat Webapps Dir
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USERNAME }}
          password: ${{ secrets.TEST_PW }}
          port: ${{ secrets.TEST_PORT }}
          source: /home/runner/work/adminservice/adminservice/target/staging-admin-service.war
          target: /opt/server/account_admin/webapps/
          strip_components: 3 # this is important

      - name: Restart the Service to Deploy the War File
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USERNAME }}
          password: ${{ secrets.TEST_PW }}
          port: ${{ secrets.TEST_PORT }}
          script: |
            sudo systemctl restart account_admin